export const ALL_ASSIGNMENT_REQUEST = 'ALL_ASSIGNMENT_REQUEST';
export const ALL_ASSIGNMENT_SUCCESS = 'ALL_ASSIGNMENT_SUCCESS';
export const ALL_ASSIGNMENT_FAIL = 'ALL_ASSIGNMENT_FAIL';

export const ASSIGNMENT_DETAILS_REQUEST = 'ASSIGNMENT_DETAILS_REQUEST';
export const ASSIGNMENT_DETAILS_SUCCESS = 'ASSIGNMENT_DETAILS_SUCCESS';
export const ASSIGNMENT_DETAILS_FAIL = 'ASSIGNMENT_DETAILS_FAIL';

export const CREATE_ASSIGNMENT_REQUEST = 'CREATE_ASSIGNMENT_REQUEST';
export const CREATE_ASSIGNMENT_SUCCESS = 'CREATE_ASSIGNMENT_SUCCESS';
export const CREATE_ASSIGNMENT_RESET = 'CREATE_ASSIGNMENT_RESET';
export const CREATE_ASSIGNMENT_FAIL = 'CREATE_ASSIGNMENT_FAIL';

export const UPDATE_ASSIGNMENT_REQUEST = 'UPDATE_ASSIGNMENT_REQUEST';
export const UPDATE_ASSIGNMENT_SUCCESS = 'UPDATE_ASSIGNMENT_SUCCESS';
export const UPDATE_ASSIGNMENT_RESET = 'UPDATE_ASSIGNMENT_RESET';
export const UPDATE_ASSIGNMENT_FAIL = 'UPDATE_ASSIGNMENT_FAIL';

export const DELETE_ASSIGNMENT_REQUEST = 'DELETE_ASSIGNMENT_REQUEST';
export const DELETE_ASSIGNMENT_SUCCESS = 'DELETE_ASSIGNMENT_SUCCESS';
export const DELETE_ASSIGNMENT_RESET = 'DELETE_ASSIGNMENT_RESET';
export const DELETE_ASSIGNMENT_FAIL = 'DELETE_ASSIGNMENT_FAIL';

export const SEARCH_ASSIGNMENT_REQUEST = 'SEARCH_ASSIGNMENT_REQUEST';
export const SEARCH_ASSIGNMENT_SUCCESS = 'SEARCH_ASSIGNMENT_SUCCESS';
export const SEARCH_ASSIGNMENT_FAIL = 'SEARCH_ASSIGNMENT_FAIL';

export const ALL_COMMENT_REQUEST = 'ALL_COMMENT_REQUEST';
export const ALL_COMMENT_SUCCESS = 'ALL_COMMENT_SUCCESS';
export const ALL_COMMENT_FAIL = 'ALL_COMMENT_FAIL';

export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_RESET = 'CREATE_COMMENT_RESET';
export const CREATE_COMMENT_FAIL = 'CREATE_COMMENT_FAIL';

export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_RESET = 'DELETE_COMMENT_RESET';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';

export const SORT_LEADER_REQUEST = 'SORT_LEADER_REQUEST';
export const SORT_LEADER_SUCCESS = 'SORT_LEADER_SUCCESS';
export const SORT_LEADER_FAIL = 'SORT_LEADER_FAIL';

export const SORT_LEADER_DESC_REQUEST = 'SORT_LEADER_DESC_REQUEST';
export const SORT_LEADER_DESC_SUCCESS = 'SORT_LEADER_DESC_SUCCESS';
export const SORT_LEADER_DESC_FAIL = 'SORT_LEADER_DESC_FAIL';

export const SORT_EMPLOYEE_REQUEST = 'SORT_EMPLOYEE_REQUEST';
export const SORT_EMPLOYEE_SUCCESS = 'SORT_EMPLOYEE_SUCCESS';
export const SORT_EMPLOYEE_FAIL = 'SORT_EMPLOYEE_FAIL';

export const SORT_EMPLOYEE_DESC_REQUEST = 'SORT_EMPLOYEE_DESC_REQUEST';
export const SORT_EMPLOYEE_DESC_SUCCESS = 'SORT_EMPLOYEE_DESC_SUCCESS';
export const SORT_EMPLOYEE_DESC_FAIL = 'SORT_EMPLOYEE_DESC_FAIL';

export const SORT_DATE_REQUEST = 'SORT_DATE_REQUEST';
export const SORT_DATE_SUCCESS = 'SORT_DATE_SUCCESS';
export const SORT_DATE_FAIL = 'SORT_DATE_FAIL';

export const SORT_DATE_DESC_REQUEST = 'SORT_DATE_DESC_REQUEST';
export const SORT_DATE_DESC_SUCCESS = 'SORT_DATE_DESC_SUCCESS';
export const SORT_DATE_DESC_FAIL = 'SORT_DATE_DESC_FAIL';

export const CLEAR_ERROR = 'CLEAR_ERROR';