export const ALL_GROUP_REQUEST = 'ALL_GROUP_REQUEST';
export const ALL_GROUP_SUCCESS = 'ALL_GROUP_SUCCESS';
export const ALL_GROUP_FAIL = 'ALL_GROUP_FAIL';

export const CREATE_GROUP_REQUEST = 'CREATE_GROUP_REQUEST';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_RESET = 'CREATE_GROUP_RESET';
export const CREATE_GROUP_FAIL = 'CREATE_GROUP_FAIL';

export const UPDATE_GROUP_REQUEST = 'UPDATE_GROUP_REQUEST';
export const UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS';
export const UPDATE_GROUP_RESET = 'UPDATE_GROUP_RESET';
export const UPDATE_GROUP_FAIL = 'UPDATE_GROUP_FAIL';

export const GROUP_DETAILS_REQUEST = 'GROUP_DETAILS_REQUEST';
export const GROUP_DETAILS_SUCCESS = 'GROUP_DETAILS_SUCCESS';
export const GROUP_DETAILS_FAIL = 'GROUP_DETAILS_FAIL';

export const DELETE_GROUP_REQUEST = 'DELETE_GROUP_REQUEST';
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS';
export const DELETE_GROUP_RESET = 'DELETE_GROUP_RESET';
export const DELETE_GROUP_FAIL = 'DELETE_GROUP_FAIL';

export const CLEAR_ERROR = 'CLEAR_ERROR';